CREATE TABLE focus_session (
                               id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               task_label  VARCHAR(255) NOT NULL,
                               started_at  TIMESTAMPTZ  NOT NULL,
                               ended_at    TIMESTAMPTZ
);