CREATE EXTENSION IF NOT EXISTS timescaledb;

CREATE TABLE vital_reading (
                               id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
                               session_id   BIGINT           NOT NULL REFERENCES focus_session (id),
                               recorded_at  TIMESTAMPTZ      NOT NULL,
                               pulse        DOUBLE PRECISION,
                               breathing    DOUBLE PRECISION,
                               blinks       DOUBLE PRECISION,
                               PRIMARY KEY (id, recorded_at)
);
SELECT create_hypertable('vital_reading', 'recorded_at');

CREATE TABLE state_decision (
                                id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                session_id   BIGINT       NOT NULL REFERENCES focus_session (id),
                                decided_at   TIMESTAMPTZ  NOT NULL,
                                state        VARCHAR(20)  NOT NULL,   -- focus / stress / neutral
                                reason       TEXT,
                                suggestion   TEXT,
                                PRIMARY KEY (id, decided_at)
);
SELECT create_hypertable('state_decision', 'decided_at');